#
# Module manifest for module 'PSLockScreenSlideShow'
#
# Generated by: Frank Lindenblatt (Flittermelint)
#
# Updated on: 2024-08-08
#
# Inspired by:  https://github.com/nccgroup/Change-Lockscreen 
#
@{
    RootModule        = 'PSLockScreenSlideShow.psm1'

    ModuleVersion     = '0.0.1'

    GUID              = '96e1d3ad-98d1-4daa-a150-9585c9e97df5'

    Author            = 'Frank Lindenblatt (Flittermelint)'

    Copyright         = 'Copyright (c) 2024 Frank Lindenblatt (Flittermelint), licensed under the MIT License.'

    Description       = 'set single lockscreen image or display multiple images as slideshow'

    PowerShellVersion = '5.1'

    FileList          = @('PSLockScreenSlideShow.ps1')

    PrivateData = @{

        PSData = @{

            Tags       = @('powershell', 'lockscreen', 'slideshow', 'image')

            ProjectUri = 'https://github.com/Flittermelint/PSLockScreenSlideShow'

            LicenseUri = 'https://github.com/Flittermelint/PSLockScreenSlideShow/raw/main/LICENSE'

            IconUri    = 'https://github.com/Flittermelint/PSLockScreenSlideShow/raw/main/Images/PSLockScreenSlideShow.Logo.png'
        }
    }
}
